services:
  api:
    build:
      context: .
      target: development
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - DB_HOST=host.docker.internal
    ports:
      - ${APP_PORT}:${APP_PORT}
    command: npm run start:dev
    depends_on:
      - database
  database:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - 3306:3306
    volumes:
      - docker-nest-mysql:/var/lib/mysql
volumes:
  docker-nest-mysql:
